language: node_js
node_js:
- 'node'
sudo: false
cache:
- npm

branches:
  only:
  - master

before_script:
- npm install gitbook-cli

script:
- gitbook build
- mv _book/* .

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
